//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokTakip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demirbas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demirbas()
        {
            this.OdaDemirbasAtama = new HashSet<OdaDemirbasAtama>();
            this.Stok = new HashSet<Stok>();
        }
    
        public int demirbasId { get; set; }
        public string demirbasAdi { get; set; }
        public decimal fiyat { get; set; }
        public System.DateTime alımTarihi { get; set; }
        public int demirbasTuruId { get; set; }
        public int adet { get; set; }
        public int silindiMi { get; set; }
        public string model { get; set; }
        public string marka { get; set; }
    
        public virtual DemirbasTur DemirbasTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdaDemirbasAtama> OdaDemirbasAtama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stok> Stok { get; set; }
    }
}
