//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokTakip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int kullaniciId { get; set; }
        public string kullaniciAdi { get; set; }
        public int Yetki { get; set; }
        public string sifre { get; set; }
        public int personelId { get; set; }
        public bool aktifMi { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
