//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokTakip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oda()
        {
            this.OdaDemirbasAtama = new HashSet<OdaDemirbasAtama>();
        }
    
        public int odaId { get; set; }
        public int departmanId { get; set; }
        public int odaKat { get; set; }
        public string odaNumarasi { get; set; }
        public Nullable<int> personelId { get; set; }
    
        public virtual Personel Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdaDemirbasAtama> OdaDemirbasAtama { get; set; }
        public virtual Departman Departman { get; set; }
    }
}

namespace stokTakip.Model.Model1.edmx.Model1.tt
{
    public class stokTakipdbEntities6
    {
    }
}