//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokTakip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaDemirbasAtama
    {
        public int odaDemirbasId { get; set; }
        public int odaId { get; set; }
        public int demirbasId { get; set; }
        public int adet { get; set; }
        public string demirbasKodu { get; set; }
    
        public virtual Demirbas Demirbas { get; set; }
        public virtual Oda Oda { get; set; }
    }
}
